name: images

on:
  push:
    branches:
      - '**'

jobs:
  devcontainer:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    permissions:
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: image
      uses: ./.github/workflows/actions/devcontainer
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
